### ISSUE TITLE
Old-style PHP constructor in multisafepay class

### ISSUE THREAD

**Issue by siliconforks** [MultiSafepay/Zencart#3]
The [multisafepay class](https://github.com/MultiSafepay/Zencart/blob/3.0.0/includes/modules/payment/multisafepay.php#L51) has an old-style constructor and this generates a warning when the class is used:

Methods with the same name as their class will not be constructors in a future version of PHP; multisafepay has a deprecated constructor in ... includes/modules/payment/multisafepay.php on line 28.

**Comment by Ronald-MultiSafepay** [comment]
@siliconforks 
Thank you for reporting this issue.
We will keep you updated as soon as we have investigate this issue.

**Comment by Ronald-MultiSafepay** [comment]
@siliconforks 
On github we just released v3.1.0 of the ZenCart plugin 
This version includes a solution for the issue reported by you.
