### ISSUE TITLE
Use of undefined constant MODULE_PAYMENT_MULTISAFEPAY_TEXT_TITLE in notify_checkout.php

### ISSUE THREAD

**Issue by siliconforks** [MultiSafepay/Zencart#4]
The [notify_checkout.php](https://github.com/MultiSafepay/Zencart/blob/master/ext/modules/payment/multisafepay/notify_checkout.php) script instantiates the `multisafepay` class without having first included its language file.  This generates a number of warnings like this:

Use of undefined constant MODULE_PAYMENT_MULTISAFEPAY_TEXT_TITLE - assumed 'MODULE_PAYMENT_MULTISAFEPAY_TEXT_TITLE' (this will throw an Error in a future version of PHP) in ... includes/modules/payment/multisafepay.php on line 56.

It does include a language file [later in the script](https://github.com/MultiSafepay/Zencart/blob/3.0.0/ext/modules/payment/multisafepay/notify_checkout.php#L88), but that is too late to prevent the warnings.

I'm not sure if there's an easy way to fix this.  It does not seem possible to include the language file at the beginning of the script, because it does not yet know what language file to use.  (And it does not seem possible to include all language files, because they all define the `MODULE_PAYMENT_MULTISAFEPAY_TEXT_TITLE` constant.)

**Comment by Ronald-MultiSafepay** [comment]
@siliconforks 
Thank you for reporting this issue.
We will keep you updated as soon as we have investigate this issue.

**Comment by Ronald-MultiSafepay** [comment]
@siliconforks
On github we just released v3.1.0 of the ZenCart plugin
This version includes a solution for the issue reported by you.
