### ISSUE TITLE
PHP warnings for multisafepay_fastcheckout.php

### ISSUE THREAD

**Issue by siliconforks** [MultiSafepay/Zencart#5]
I'm seeing some PHP warnings in a site's log files regarding `includes/modules/payment/multisafepay_fastcheckout.php`:

```
PHP Warning: Declaration of multisafepay_fastcheckout::getShoppingCart() should be compatible with multisafepay::getShoppingCart($order)
PHP Warning: Declaration of multisafepay_fastcheckout::parseAddress($street_address) should be compatible with multisafepay::parseAddress($address1, $address2 = '')
PHP Warning: Declaration of multisafepay_fastcheckout::checkout_notify() should be compatible with multisafepay::checkout_notify($manual_status = '')
```

**Comment by danielcivit** [comment]
Hi @siliconforks.

Our most sincere apologies for the long time without reply.  The truth is that this ticket has been off our radar for a long time.

We are currently not providing updates for this plugin, however, if this continues to be an important issue for you, we invite you to write an email to integrations@multisafepay.com, indicating the ID of the associated merchant related with your request. In this way an account manager from MultiSafepay will be able to escalate the ticket with our product owner and consider your request.
